### ISSUE TITLE
ERRO HTTP 500

### ISSUE THREAD

**Issue by Matheus-Boone** [nilsonpessim/zabbix-navigator#1]
Olá, uso o Zabbix 6.0  com o Centos8 aqui, eu até consigo fazer aparecer o menu personalizado jogando os arquivos para dentro do meu server, mas toda vez que tento usar alguma função do menu personalizado o Zabbix me encaminha para uma pagina dando o erro 500, tentei também usar o Zabbix 5.0 com a versão dos arquivos para o mesmo e o problema persistiu

**Comment by nilsonpessim** [comment]
Foi identificado no CentOS, que o arquivo `zabbix.conf.php` contendo as configurações padrão do sistema, é salvo em um diretório diferente do sistema Ubuntu/Debian, que foi o sistema base de nossos testes, dessa forma, ocasionando um erro de processamento de arquivo na linguagem PHP.

Para resolver o problema, é necessário copiar o arquivo  `zabbix.conf.php` para o diretório `conf`, além da alteração da permissão para 644:

```
Copiar Arquivo -> cp /etc/zabbix/web/zabbix.conf.php /usr/share/zabbix/conf/zabbix.conf.php
Atribuir Permissão -> chmod 644 /usr/share/zabbix/conf/zabbix.conf.php
```

Após este ajuste, a página irá carregar corretamente o APP.

OBS: Não é necessário alterar nenhuma linha de códigos nos arquivos fonte.
