### ISSUE TITLE
Adicionar um botão copiar na ferramenta

### ISSUE THREAD

**Issue by ttamiozzo** [nilsonpessim/zabbix-navigator#2]
Olá Nilson, primeiramente muito obrigado pela ferramenta, agiliza o processo do dia a dia usando o Zabbix demais.... E a facilidade na instalação é absurda! Parabéns!

Gostaria de saber se é possível adicionar um botão com "Copiar IP do Host" pois muitas vezes temos hosts com acessos de SSH, Telnet ou Winbox que não usam as portas padrões... E esse botão facilitaria ainda mais!

Obrigado!

**Comment by nilsonpessim** [comment]
Notas da Versão 1.5.1 do Zabbix Navigator.

* `Versão 1.5.1 - 16/12/2022`
  * Adicionado Opção para acesso via RFB com o VNC Viewer.
  * Adicionado Opção para copiar IP do Host.
  * O arquivo Windows.reg foi reformulado.

Link para Download: 
https://github.com/nilsonpessim/zabbix-navigator/releases/tag/V1.5.1
