### ISSUE TITLE
Página branca sem dados

### ISSUE THREAD

**Issue by brungaspar** [nilsonpessim/zabbix-navigator#3]
Uma dúvida, coloquei os arquivos na pasta como pediu, no entanto minha esturtura é fragmentada, ou seja, existe um zabbix-web, zabbix-sql, zabbix-server... fiz a configuração no zabbix web, apareceram as novas opções, mas quando eu clico como copiar o endereço, abre uma nova página, mas aparece tudo em branco. O que pode ser?

**Comment by nilsonpessim** [comment]
Olá, a sua página abre em branco apenas quando clica na opção de copiar o IP ? 
Se sim, tente manter os arquivos na raiz do seu servidor as pastas `js` e `plugins`
se possível mande capturas de tela contendo inclusive a URL para facilitar mais o entendimento.

**Comment by brungaspar** [comment]
Em todas as opções quando eu clico, ele abre uma janela em branco. Como senão conseguisse pegar as configurações do arquivo php.

**Comment by brungaspar** [comment]
![16730050112297477427648044708419](https://user-images.githubusercontent.com/22779368/211005109-84da37af-338b-47ba-8621-bd14a6389453.jpg)

**Comment by brungaspar** [comment]
![16730050439905768572257492389641](https://user-images.githubusercontent.com/22779368/211005165-f168b246-0c28-494b-b664-7da55f28867e.jpg)

**Comment by brungaspar** [comment]
![Uploading 1673005067496467342873583995482.jpg…]()

**Comment by nilsonpessim** [comment]
@brungaspar está utilizando o PostgreeSQL ?

**Comment by nilsonpessim** [comment]
Veja se resolve para você:

https://github.com/nilsonpessim/zabbix-navigator/issues/4
