### ISSUE TITLE
Pagina http não abre. 

### ISSUE THREAD

**Issue by AlOliveira88** [nilsonpessim/zabbix-navigator#4]
Boa noite.

Parabéns e obrigado pela partilha.
Realizei todos os passos pretendidos, mas a pagina do equipamento não abre, fica em branco...
Estou a utilizar zabbix 6.2 com postgreSQL.

Alguma sugestão???? 
Obrigado

;)

**Comment by nilsonpessim** [comment]
Olá, o problema ocorre pois a aplicação estava sem suporte ao PostgreSQL, para funcionar no seu banco de dados, é necessário alterar o driver de conexão com o PDO, apenas alterando o driver de *mysql* para *pgsql*

$PDO = new PDO("pgsql:host={$hostname};dbname={$database}", $username, $password);

Os arquivos *menupopup.php* de todas as versões, foram corrigidos para suportar essa nova condição, adicionando apenas uma variável para que seja possível alterar de forma manual, mas em breve, lançarei uma versão onde o sistema irá identificar a versão do banco, e alterar automaticamente o driver.

Essa variável ficou documentada, logo após a declaração do arquivo de require.

Espero ter ajudado.

**Comment by AlOliveira88** [comment]
Olá.

Com a alteração, ficou a funcionar tudo bem.

Obrigado

**Comment by nilsonpessim** [comment]
Notas da versão 1.5.2

https://github.com/nilsonpessim/zabbix-navigator/releases/tag/V1.5.2
