### ISSUE TITLE
Não aparece o menu

### ISSUE THREAD

**Issue by frazaorc** [nilsonpessim/zabbix-navigator#5]
Olá, meu zabbix é o 6.0.10 com postgres e sistema operacional Redhat 8 em 3 camadas. realizei todo o procedimento e não apareceu o menu. Restartei o server  e ficou com o erro de zabbix não está rodando e tive restartar a camada do front end ou seja o PHP e HTTP.
Li uns Issues mas achei melhor abrir esse para verificar.

Obrigado

**Comment by nilsonpessim** [comment]
Olá, verifique alguns passos: 

* O pacote instalado é para a versão 6.0 ? 
* Consegue abrir manualmente o arquivo /menupopup.php ?
* Qual é a versão do PHP ?

Por gentileza, nos encaminhe alguns prints de evidencias sobre o seu erro.

**Comment by frazaorc** [comment]
-->Sim o pacote foi da versão 6.0 a versão instalada 6.0.10
-->PHP 7.2
--> sim consigo abrir
--> Não apresenta erros, apenas permanece como se não tivesse feito nada, o menu continua igual.

**Comment by nilsonpessim** [comment]
Olá, @frazaorc ainda com os erros ?

**Comment by frazaorc** [comment]
Acabei não insistindo, teria que retomar.
Hoje não estou usando.

Em qui., 17 de ago. de 2023 14:26, Nilson Pessim ***@***.***>
escreveu:
