### ISSUE TITLE
Problemas ao abrir o host com SSH

### ISSUE THREAD

**Issue by ivanmirandaf** [nilsonpessim/zabbix-navigator#6]
Olá, fiz todo o processo de importação e configuração dos arquivos no Zabbix Server, mas não consegui abrir o host com SSH. 
O browser até pede permissão para abrir o **URL:SSH Protocol**, mas ao aceitar não acontece nada.
Tive êxito com winbox, winmrt e vnc.

**Zabbix:** 6.0.13
**SO:** Debian 11
**Web Server:** Nginx 1.18.0

**Comment by nilsonpessim** [comment]
Olá, tudo bem?!

Acabei de fazer um teste com um cenário semelhante ao seu e sem nenhum erro, abriu perfeitamente o Putty, 2 possíveis problemas conhecidos por mim:
* Confira se o caminho do Putty está correto no seu PC:  ```C:\zabbix\app\Putty.exe```
* Se seu Windows já tiver outras entradas no registro para o protocolo de SSH, como quando instalamos o pacote o EVE-NG Client, pode dar conflito e fazer com que não funcione.

**Comment by ivanmirandaf** [comment]
Fiz o teste em outra máquina e o Putty funcionou certinho.

Como faço para consultar se existe outras entradas no registro para o protocolo SSH? Fiz algumas consultas e acabei ficando perdido. kkkk

**Comment by nilsonpessim** [comment]
Top, ótimo que funcionou @ivanmirandaf .

Voce pode realizar uma busca pela palavra SSH no editor de registro do Windows (regedit), mas pode ser que existam vários registros com o mesmo nome, como não tem especificado qual é o sistema, ou app que modificou o seu registro com a chave do SSH, ele pode ser uma, ou várias chaves, além do desenvolvedor poder personalizar o caminho e deixar padronizado as configurações, no nosso caso com o Zabbix Navigator, eu mantive em ```HKEY_CLASSES_ROOT\SSH```. 

Irei encerrar o tópico, mais qualquer dúvida relacionado pode abrir um novo issue. 
Obrigado pelo contato, até mais!
